### ISSUE TITLE
Get stan-mode working on MELPA stable (perhaps split repo)

### ISSUE THREAD

**Issue by jrnold** [stan-dev/stan-mode#42]
Proposal to split the repo into `stan-mode`, `stan-snippets`, and potentially other packages if there are additional emacs packages.

The purpose of this would be to work nicer with [MELPA](http://melpa.org/#/), which is largest emacs package repository these days. There are two MELPA archives: the normal one, [MELPA](http://melpa.org/#/), which builds from source whenever changes are pushed, and [MELPA stable](http://melpa.org/#/). MELPA stable builds a package from the commit with a tag that looks like a version number and may be prefixed by `v.`. Since this repository contains multiple packages on MELPA: `stan-mode` and `stan-snippets`, I would rather not have a single version tag for multiple packages.  So my options right now are: 

1. single version tag for this repo
2. split the repo
3. file an issue with MELPA

Any thoughts on this @syclik @bob-carpenter ?

This caused a problem mentioned in this stan-users [thread](https://groups.google.com/forum/#!searchin/stan-users/stan-mode/stan-users/qbMGhZ9GYfE/PIcO6hPX0j4J). A user was having an error, which was due to them using v4.0.0 of stan-mode which is the current "stable" version on MELPA stable, because after that I started using tags for the version of each package, `stan-mode`, `stan-snippets`, `ac-stan`. My response over email:

> Now, I see the problem. The current version of stan-mode is fine, buit MELPA > stable has an unstable > version of stan-snippets and stan-mode that is several versions back. I wasn't using MELPA stable and > hadn't realized how MELPA stable generated its "stable" versions, which is looking for a tag  The way
> that melpa-stable determines a new version is looking for a tag in the repo starting with "v". Since the stan-mode repo contains several different emacs modes, I hadn't been following that convention since there are several modes contained in it, so I am giving each its own version. I'll need to figure out how to > handle MELPA - either by using a global version number, splitting the repository, or submitting an issue to melpa. For now it it best to use the current MELPA version.

**Comment by bob-carpenter** [comment]
> On Jul 28, 2015, at 10:23 PM, Jeffrey Arnold <notifications@github.com> wrote:
> 
> Proposal to split the repo into stan-mode, stan-snippets, and potentially other packages if there are additional emacs packages.
> 
> The purpose of this would be to work nicer with MELPA, which is largest emacs package repository these days. There are two MELPA archives: the normal one, MELPA, which builds from source whenever changes are pushed, and MELPA stable. MELPA stable builds a package from the commit with a tag that looks like a version number and may be prefixed by v.. Since this repository contains multiple packages on MELPA: stan-mode and stan-snippets, I would rather not have a single version tag for multiple packages. So my options right now are:
> 
> 	• single version tag for this repo
> 	• split the repo
> 	• file an issue with MELPA
> Any thoughts on this @syclik @bob-carpenter ?

Fine by me if it makes deployment easier.  And thanks so much for
keeping it up to date.

- Bob
>

**Comment by jrnold** [comment]
Great. I'm trying a few other things first (e.g. milkypostman/melpa#2972) . If I need to create new repositories, I'll let you know. At the moment I don't have permissions to do so within stan-dev.

**Comment by syclik** [comment]
That sounds good. I trust your judgement in all things emacs-mode.

**Comment by jrnold** [comment]
Don't go too far. `stan-mode` mostly serves to remind me of how minimal my elisp knowledge is.

**Comment by jrnold** [comment]
Resolved by using the same version number for all stan packages in this.
