### ISSUE TITLE
Remove dependency on cc-mode

### ISSUE THREAD

**Issue by jrnold** [stan-dev/stan-mode#44]
This is a longer-run issue. Remove dependency on `cc-mode` and write an indentation engine based on [smie](https://www.gnu.org/software/emacs/manual/html_node/elisp/SMIE.html). I can translate the Stan BNF to an operator-precedence grammar that `smie` uses.  Removing the reliance on `cc-mode` would be useful because as features are added to the Stan language, it will diverge from `C++` syntax.

**Comment by jrnold** [comment]
Examples of modes using `smie` from a github [search](https://github.com/search?l=emacs-lisp&q=%22require+%27smie%22&ref=searchresults&type=Code&utf8=%E2%9C%93)

**Comment by jrnold** [comment]
@bob-carpenter stan mode has been having some issues with using the built-in cc-mode to parse the grammar (see #47 ). One idea that I've been sitting on is to use emac's [smie](https://www.gnu.org/software/emacs/manual/html_node/elisp/SMIE.html) to write a new indentation engine. Smie uses an operator precedence grammar for its indentation engine because that is usually "good enough" :tm: for indentation (with edge cases handled by custom code). Since you are the languages expert, what do you think?

**Comment by jrnold** [comment]
From #47 link to smie c-mode http://git.savannah.gnu.org/cgit/emacs/elpa.git/tree/packages/sm-c-mode

**Comment by bob-carpenter** [comment]
I'm so lazy I haven't even tried installing the latest stan mode,
though I've seen Daniel using it and it looks awesome.
Auto indent should be good enough for us---we use bog standard
indentation other than for the named model blocks (which should format
as while loops without a condition).

- Bob

**Comment by jrnold** [comment]
s/lazy/efficient/g

**Comment by kaz-yos** [comment]
Just adding a link to the current Language Syntax:
https://mc-stan.org/docs/2_20/reference-manual/language-syntax.html

**Comment by kaz-yos** [comment]
As of now, `cc-mode` is still a powerful working solution.
