### ISSUE TITLE
spacemacs ess layer

### ISSUE THREAD

**Issue by vixr** [stan-dev/stan-mode#46]
Can spacemacs support be added? Either as part of the ess layer, or as a separate layer?

**Comment by jrnold** [comment]
I haven't used spacemacs, so I don't have any plans. But I'd be happy to accept a pull-request that implements the needed functionality :-)

**Comment by fernandomayer** [comment]
I have enabled the `extra-langs` layer and it installs `stan-mode`. Worked fine for me.

See [here](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/extra-langs).
